version: '3.9'

services:
  dnscontrol:
    container_name: dstack-dnscontrol
    volumes:
      - ..:/usr/share/rtldev-middleware-dnscontrol-dnsconfig:cached
    build:
      context: .
      dockerfile: Dockerfile
